### ISSUE TITLE
发现2个小问题

### ISSUE THREAD

**Issue by vaaydev** [awinds/xaink#1]
1、如果网站描述写太长的话，前台头像就会变现。
![微信截图_20240712185405](https://github.com/user-attachments/assets/ab5d1bc0-5c94-41fb-bdd4-bf797206efae)

2、PHP8 环境下，搜索会出现500，我是用typecho1.2.1版本的。

![微信截图_20240712185424](https://github.com/user-attachments/assets/2f97f7a5-6e63-48fe-bc54-cc59faa07ab2)

**Comment by awinds** [comment]
感谢反馈，已修改

**Comment by vaaydev** [comment]
> 感谢反馈，已修改

还有一个问题，标签太多或太长，也会变形

![微信截图_20240716100928](https://github.com/user-attachments/assets/16109220-1d5b-4dc9-88d1-16cd0ee3b748)
![微信截图_20240716100959](https://github.com/user-attachments/assets/723466f2-3e92-4e13-a772-7f638c7d44c3)

**Comment by awinds** [comment]
已更新，正常标签不会太长和太多，一般一行就能显示了，现在改成换行显示了
