### ISSUE TITLE
建议添加站点logo时，分为日间和夜间两个

### ISSUE THREAD

**Issue by smireshang** [awinds/xaink#2]
一个logo不好兼顾两种场景的显示效果

**Comment by spmh** [comment]
把LOGO背景透明化，黑色换成灰色。

**Comment by smireshang** [comment]
> 把LOGO背景透明化，黑色换成灰色。

不失为一种妥协的解决方式

**Comment by awinds** [comment]
一般用户比较懒，不会专门做2套logo，做一个颜色比较亮的透明logo，适配黑白是没有问题的

**Comment by smireshang** [comment]
> 一般用户比较懒，不会专门做2套logo，做一个颜色比较亮的透明logo，适配黑白是没有问题的

嗯，已修改
